In [3]:
import pandas as pd

df = pd.read_csv("../data/raw/immigrant_data.csv")
df.head(10)

,person_id,country_of_origin,entry_type,previous_profession,current_profession,years_in_us,english_level,education_level,hours_per_week,annual_income,stress_level,job_satisfaction,employment_type
0,1,Mexico,undocumented,farmer,IT,6,advanced,high_school,43,103069,9,7,part-time
1,2,Philippines,undocumented,farmer,IT,3,advanced,high_school,39,91604,9,8,self-employed
2,3,China,student_visa,accountant,delivery,10,intermediate,high_school,60,46283,4,3,full-time
3,4,China,work_visa,driver,office,7,advanced,associate,59,42814,7,7,full-time
4,5,India,tourist_visa,nurse,office,9,basic,master,41,29941,4,8,full-time
5,6,Colombia,undocumented,farmer,office,5,advanced,high_school,54,32779,7,5,part-time
6,7,China,undocumented,accountant,construction,2,intermediate,master,62,35421,5,5,self-employed
7,8,Philippines,marriage,engineer,cleaning,8,advanced,associate,56,35716,10,7,part-time
8,9,Mexico,work_visa,accountant,construction,8,advanced,master,59,56476,9,4,self-employed
9,10,Brazil,marriage,construction_worker,cleaning,1,advanced,high_school,55,33179,8,3,full-time

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   person_id            300 non-null    int64
 1   country_of_origin    300 non-null    object
 2   entry_type           300 non-null    object
 3   previous_profession  300 non-null    object
 4   current_profession   300 non-null    object
 5   years_in_us          300 non-null    int64
 6   english_level        300 non-null    object
 7   education_level      300 non-null    object
 8   hours_per_week       300 non-null    int64
 9   annual_income        300 non-null    int64
 10  stress_level         300 non-null    int64
 11  job_satisfaction     300 non-null    int64
 12  employment_type      300 non-null    object
dtypes: int64(6), object(7)
memory usage: 30.6+ KB

In [4]:
df.shape

(300, 13)

In [5]:
df.columns

Index(['person_id', 'country_of_origin', 'entry_type', 'previous_profession',
       'current_profession', 'years_in_us', 'english_level', 'education_level',
       'hours_per_week', 'annual_income', 'stress_level', 'job_satisfaction',
       'employment_type'],
      dtype='object')

In [ ]:
# DADOS FALTANTES
df.isnull().sum()

person_id              0
country_of_origin      0
entry_type             0
previous_profession    0
current_profession     0
years_in_us            0
english_level          0
education_level        0
hours_per_week         0
annual_income          0
stress_level           0
job_satisfaction       0
employment_type        0
dtype: int64

In [7]:
(df.isnull().sum() / len(df)) * 100

person_id              0.0
country_of_origin      0.0
entry_type             0.0
previous_profession    0.0
current_profession     0.0
years_in_us            0.0
english_level          0.0
education_level        0.0
hours_per_week         0.0
annual_income          0.0
stress_level           0.0
job_satisfaction       0.0
employment_type        0.0
dtype: float64

In [8]:
df.describe()

,person_id,years_in_us,hours_per_week,annual_income,stress_level,job_satisfaction
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,150.500000,6.403333,49.553333,54282.436667,7.130000,6.060000
std,86.746758,3.410684,8.067057,25321.625208,1.961102,1.937933
min,1.000000,1.000000,38.000000,25104.000000,4.000000,3.000000
25%,75.750000,4.000000,43.000000,35810.500000,5.000000,4.000000
50%,150.500000,6.000000,48.000000,45466.000000,7.000000,6.000000
75%,225.250000,9.000000,56.000000,70952.000000,9.000000,8.000000
max,300.000000,12.000000,70.000000,128863.000000,10.000000,9.000000

In [9]:
df.describe(include="all")

,person_id,country_of_origin,entry_type,previous_profession,current_profession,years_in_us,english_level,education_level,hours_per_week,annual_income,stress_level,job_satisfaction,employment_type
count,300.000000,300,300,300,300,300.000000,300,300,300.000000,300.000000,300.000000,300.000000,300
unique,NaN,6,5,8,6,NaN,3,4,NaN,NaN,NaN,NaN,3
top,NaN,China,work_visa,farmer,cleaning,NaN,advanced,master,NaN,NaN,NaN,NaN,full-time
freq,NaN,62,68,45,60,NaN,119,83,NaN,NaN,NaN,NaN,105
mean,150.500000,NaN,NaN,NaN,NaN,6.403333,NaN,NaN,49.553333,54282.436667,7.130000,6.060000,NaN
std,86.746758,NaN,NaN,NaN,NaN,3.410684,NaN,NaN,8.067057,25321.625208,1.961102,1.937933,NaN
min,1.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,38.000000,25104.000000,4.000000,3.000000,NaN
25%,75.750000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,43.000000,35810.500000,5.000000,4.000000,NaN
50%,150.500000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,48.000000,45466.000000,7.000000,6.000000,NaN
75%,225.250000,NaN,NaN,NaN,NaN,9.000000,NaN,NaN,56.000000,70952.000000,9.000000,8.000000,NaN
max,300.000000,NaN,NaN,NaN,NaN,12.000000,NaN,NaN,70.000000,128863.000000,10.000000,9.000000,NaN

In [10]:
df["country_of_origin"].value_counts()

country_of_origin
China          62
Brazil         51
Colombia       50
India          49
Mexico         48
Philippines    40
Name: count, dtype: int64

In [11]:
df.columns.tolist()

['person_id',
 'country_of_origin',
 'entry_type',
 'previous_profession',
 'current_profession',
 'years_in_us',
 'english_level',
 'education_level',
 'hours_per_week',
 'annual_income',
 'stress_level',
 'job_satisfaction',
 'employment_type']

In [12]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)

In [13]:
df.columns

Index(['person_id', 'country_of_origin', 'entry_type', 'previous_profession',
       'current_profession', 'years_in_us', 'english_level', 'education_level',
       'hours_per_week', 'annual_income', 'stress_level', 'job_satisfaction',
       'employment_type'],
      dtype='object')

In [14]:
df.to_csv("../data/processed/immigrant_data_cleaned.csv", index=False)

In [15]:
df.duplicated().sum()

0

In [16]:
df["income_per_hour"] = df["annual_income"] / (df["hours_per_week"] * 52)

In [17]:
df.to_csv("../data/processed/immigrant_data_cleaned.csv", index=False)

In [18]:
df.columns.to_list()

['person_id',
 'country_of_origin',
 'entry_type',
 'previous_profession',
 'current_profession',
 'years_in_us',
 'english_level',
 'education_level',
 'hours_per_week',
 'annual_income',
 'stress_level',
 'job_satisfaction',
 'employment_type',
 'income_per_hour']